server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authz?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: rootroot
  
  #  mvc:
  #    pathmatch:
  #      matching-strategy: ANT_PATH_MATCHER

  redis:
    host: localhost
    port: 6379
    database: 10
    password:

### 开启sql日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.lakers.mapper: debug
#
#digest:
#  type: sha
